# Exercícios

In [38]:
import numpy as np


1. Crie um array NumPy unidimensional com os números de 1 a 10.

In [39]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Crie um array NumPy bidimensional 3x3 preenchido com zeros.

In [40]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

3. Crie um array NumPy bidimensional 4x4 preenchido com uns.

In [41]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

4. Crie um array NumPy com 20 valores aleatórios entre 0 e 100.

In [42]:
np.random.randint(0,100, size=20)

array([77,  3, 64,  3, 49,  9, 18, 99, 57, 43, 78, 86, 62, 84, 93, 97, 29,
       77, 79,  7])

5. Crie um array NumPy unidimensional com espaçamento de 0.5 entre 0 e 10.

In [43]:
np.arange(0,10.5,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

6. Crie um array NumPy bidimensional 5x5 com valores aleatórios inteiros entre 1 e 100.

In [44]:
%%time
np.random.randint(1,101,size=(5,5))

CPU times: user 39 µs, sys: 24 µs, total: 63 µs
Wall time: 64.8 µs


array([[ 3, 28, 71, 86,  3],
       [33, 35, 17, 66, 44],
       [81, 58, 40, 19, 49],
       [76,  8, 75, 79, 60],
       [82, 15, 97,  6,  8]])

7. Dada a matriz A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], crie um array NumPy contendo apenas a segunda coluna da matriz A.

In [45]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A[:,1]

array([2, 5, 8])

8. Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores pares sejam substituídos por -1.

In [46]:
x = np.array([1, 2, 3, 4, 5])
x[x%2==0] = -1
display(x)

array([ 1, -1,  3, -1,  5])

9.  Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores maiores que 2 sejam substituídos por 0.


In [47]:
x = np.array([1, 2, 3, 4, 5])
x[x>2] = 0

display(x)

array([1, 2, 0, 0, 0])

10. Dado o array NumPy x = [1, 2, 3, 4, 5], normalize os valores do array de forma que a soma seja igual a 1.


In [48]:
x = np.array([1, 2, 3, 4, 5])
normalizado = x/np.sum(x)

display(normalizado, np.sum(normalizado))


array([0.06666667, 0.13333333, 0.2       , 0.26666667, 0.33333333])

1.0


11. Dada a matriz A = [[1, 2], [3, 4]] e a matriz B = [[5, 6], [7, 8]], calcule a multiplicação matricial entre A e B.


In [49]:
A = np.array([[1, 2], [3, 4]]) 
B = np.array([[5, 6], [7, 8]])
np.multiply(A, B)

array([[ 5, 12],
       [21, 32]])

12. Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos três vezes.

In [50]:
x = np.array([1, 2, 3])
x = np.tile(x, (3,))
display(x)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

13. Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos lado a lado três vezes.

In [51]:
x = np.array([1, 2, 3])
np.repeat(x,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

14. Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos verticalmente três vezes.

In [52]:
x = np.array([1, 2, 3])
np.tile(x, (3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

15. Dado o array NumPy x = [1, 2, 3], inverta a ordem dos elementos do array.

In [53]:
x = np.array([1, 2, 3])
np.flip(x)

array([3, 2, 1])