# Exercícios

In [2]:
import numpy as np


1. Crie um array NumPy unidimensional com os números de 1 a 10.

In [3]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Crie um array NumPy bidimensional 3x3 preenchido com zeros.

In [4]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

3. Crie um array NumPy bidimensional 4x4 preenchido com uns.

In [5]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

4. Crie um array NumPy com 20 valores aleatórios entre 0 e 100.

In [6]:
np.random.randint(0,100, size=20)

array([88, 83, 26, 84, 65, 46, 62, 82, 61, 94, 94, 66, 67, 65, 30, 39, 69,
       50, 16, 33])

5. Crie um array NumPy unidimensional com espaçamento de 0.5 entre 0 e 10.

In [7]:
np.arange(0,10.5,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

6. Crie um array NumPy bidimensional 5x5 com valores aleatórios inteiros entre 1 e 100.

In [8]:
%%time
np.random.randint(1,101,size=(5,5))

CPU times: user 64 µs, sys: 34 µs, total: 98 µs
Wall time: 102 µs


array([[ 5, 39, 16, 61,  9],
       [25, 37, 22, 79, 23],
       [58, 97, 22, 39, 18],
       [40, 59, 47, 11, 29],
       [20, 58, 42, 25, 54]])

7. Dada a matriz A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]], crie um array NumPy contendo apenas a segunda coluna da matriz A.

In [9]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A[:,1]

array([2, 5, 8])

8. Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores pares sejam substituídos por -1.

In [10]:
x = np.array([1, 2, 3, 4, 5])
x[x%2==0] = -1
display(x)

array([ 1, -1,  3, -1,  5])

9.  Dado o array NumPy x = [1, 2, 3, 4, 5], crie um novo array onde todos os valores maiores que 2 sejam substituídos por 0.


In [11]:
x = np.array([1, 2, 3, 4, 5])
x[x>2] = 0

display(x)

array([1, 2, 0, 0, 0])

10. Dado o array NumPy x = [1, 2, 3, 4, 5], normalize os valores do array de forma que a soma seja igual a 1.


In [12]:
x = np.array([1, 2, 3, 4, 5])
normalizado = x/np.sum(x)

display(normalizado, np.sum(normalizado))


array([0.06666667, 0.13333333, 0.2       , 0.26666667, 0.33333333])

1.0


11. Dada a matriz A = [[1, 2], [3, 4]] e a matriz B = [[5, 6], [7, 8]], calcule a multiplicação matricial entre A e B.


In [13]:
A = np.array([[1, 2], [3, 4]]) 
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

12. Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos três vezes.

In [14]:
x = np.array([1, 2, 3])
x = np.tile(x, (3,))
display(x)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

13. Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos lado a lado três vezes.

In [15]:
x = np.array([1, 2, 3])
np.repeat(x,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

14. Dado o array NumPy x = [1, 2, 3], crie um novo array com os valores de x repetidos verticalmente três vezes.

In [16]:
x = np.array([1, 2, 3])
np.tile(x, (3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

15. Dado o array NumPy x = [1, 2, 3], inverta a ordem dos elementos do array.

In [17]:
x = np.array([1, 2, 3])
np.flip(x)

array([3, 2, 1])