# Python para Análise de Dados - Numpy   

<p> Iremos aprender a trabalhar coma biblioteca Numpy.


In [1]:
# Importando a biblioteca numpy
import numpy as np

In [2]:
# Criando um array de 1 dimensão
one_dim = np.array([1,2,3,4])

In [3]:
type(one_dim)

numpy.ndarray

In [4]:
# Imprimindo um array.
one_dim.ndim

1

In [5]:
# Criando um array de 2 dimensões.
two_dim = np.array([(1,2,3), (4,5,6)])

In [6]:
# Imprimindo o array
two_dim

2

In [7]:
# Cria um array de números aleatórios.
# Um array de 5 linhas e duas dimensões.
np.random.random((5,2))

array([[0.15602492, 0.00436481],
       [0.0056985 , 0.64874345],
       [0.33440417, 0.62976834],
       [0.78467376, 0.92567222],
       [0.59192061, 0.90153326]])

In [8]:
# Cria um array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5.
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [9]:
# cria um array linear de 0 a 2 de no máximo 9 elementos.
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
# Cria um array de valores zero.
# Cria um array com 3 linhas e 4 dimensões.
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Numpy Arrays Vs Listas

- Arrays Numpy permitem fazermos operações em **arrays inteiros** de forma rápida.
- Listas não permitem operações em todos os elementos da lista.
- Para operações em todos os elementos é preciso interar sobre toda a lista.
- Listas em Python armazenam diferentes tipos de objetos
- Arrays Numpy considera todos os elementos de tipos distintos como strings


In [11]:
# Criando uma lista em Python.
lista = [1,2,3]

In [12]:
lista

[1, 2, 3]

In [13]:
# Multiplicar valores da lista por 2.
lista * 2

[1, 2, 3, 1, 2, 3]

In [14]:
# Transforme a variável lista em um array Numpy
lista = np.array(lista)

In [15]:
# Imprimindo o tipo do objeto.
type(lista)

numpy.ndarray

In [16]:
# Multiplicando cada elemento por 2.
lista * 2

array([2, 4, 6])

In [17]:
# Calcular IMC de pessoas.
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [18]:
# Faz o calculo usando as listas
pesos / altura ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [19]:
# Transforme isso em arrays numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [20]:
# Imprime o calculo de cada valor
pesos / altura **2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [6]:
# Arrays Numpy armazena elementos como strings quando estes não são inteiros ou float
a = np.array([1,3,'Casa',True])

In [7]:
a

array(['1', '3', 'Casa', 'True'], dtype='<U11')

In [23]:
a * 2 

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

In [8]:
# repete o valor do array 2 vezes.
np.tile(a, 2)

array(['1', '3', 'Casa', 'True', '1', '3', 'Casa', 'True'], dtype='<U11')

In [52]:
lista = [1,3,'Casa',True]
lista

[1, 3, 'Casa', True]

In [53]:
lista * 2 

[1, 3, 'Casa', True, 1, 3, 'Casa', True]

In [55]:
lista = [i for i in range(10,50,5)]
lista

[10, 15, 20, 25, 30, 35, 40, 45]

In [57]:
soma = 0
for i in lista:
    soma +=i
    
print('Média:' + str(soma/len(lista)))

Média:27.5


In [3]:
n_array = np.arange(10,50,5)
n_array

array([10, 15, 20, 25, 30, 35, 40, 45])

In [4]:
n_array.mean()

27.5

In [3]:
import time
l1 = list(range(100000))
l2 = np.arange(100000)

start_time = time.time()
%time for i in range(len(l1)): l1[i] = l1[i]*2
end_time = time.time()
cpu_time = end_time - start_time

print("Tempo de CPU:", cpu_time, "segundos")

start_time = time.time()
%time l = [i*2 for i in l1]
end_time = time.time()
cpu_time = end_time - start_time

print("Tempo de CPU:", cpu_time, "segundos")

start_time = time.time()
%time l2 = l2 * 2
end_time = time.time()
cpu_time = end_time - start_time

print("Tempo de CPU:", cpu_time, "segundos")
#%time for i in range(100)

Wall time: 26.2 ms
Tempo de CPU: 0.028210878372192383 segundos
Wall time: 11 ms
Tempo de CPU: 0.01307225227355957 segundos
Wall time: 0 ns
Tempo de CPU: 0.0010726451873779297 segundos


In [65]:
lista

[10, 15, 20, 25, 30, 35, 40, 45]

In [68]:
lista[0]

10

In [72]:
lista[lista>20]

TypeError: '>' not supported between instances of 'list' and 'int'

In [67]:
n_array

array([10, 15, 20, 25, 30, 35, 40, 45])

In [69]:
n_array[0]

10

In [73]:
n_array[n_array>20]

array([25, 30, 35, 40, 45])

# Métodos e Atributos Úteis

In [ ]:
# Métodos disponíveis (digite o . pressione tab).
two_dim.

In [25]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# Retorna a forma do array no formato linhas e colunas.
two_dim.shape

(2, 3)

In [27]:
# Retorna a quantidade de dimensões.
two_dim.ndim

2

In [28]:
# Imprimindo o valor máximo do array.
two_dim.max()

6

In [29]:
# Imprimindo o valor mínimo.
two_dim.min()

1

In [30]:
# Imprimindo o valor médio.
two_dim.mean()

3.5

In [31]:
# Imprimindo o desvio padrão.
two_dim.std()

1.707825127659933

In [32]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
two_dim.dtype

dtype('int32')

In [34]:
two_dim.size

6

In [35]:
# mostra a quantidade
two_dim.itemsize

4

In [36]:
# Somando todos os elementos do array.
two_dim.sum()

21

#  Transformando Arrays

In [37]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
# Gera a Transposta da Matriz (Linha -> coluna)
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [39]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
# Transforma em uma matriz de uma linha.
# È muito comum em bibliotecas como scikit-learn e Keras
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [41]:
tree = np.random.random((5,3))

In [42]:
tree.shape

(5, 3)

In [43]:
tree

array([[0.90101605, 0.33509405, 0.09516297],
       [0.73026034, 0.86340173, 0.42424879],
       [0.7992478 , 0.37531825, 0.64856213],
       [0.94368344, 0.12455872, 0.21219825],
       [0.14391759, 0.15165705, 0.29783426]])

In [44]:
# Transforma em uma matriz com 3 linhas e 5 colunas
tree.reshape(3,5)

array([[0.90101605, 0.33509405, 0.09516297, 0.73026034, 0.86340173],
       [0.42424879, 0.7992478 , 0.37531825, 0.64856213, 0.94368344],
       [0.12455872, 0.21219825, 0.14391759, 0.15165705, 0.29783426]])

In [45]:
tree.reshape(-1)

array([0.90101605, 0.33509405, 0.09516297, 0.73026034, 0.86340173,
       0.42424879, 0.7992478 , 0.37531825, 0.64856213, 0.94368344,
       0.12455872, 0.21219825, 0.14391759, 0.15165705, 0.29783426])

In [46]:
t=tree.reshape(1,15)
t

array([[0.90101605, 0.33509405, 0.09516297, 0.73026034, 0.86340173,
        0.42424879, 0.7992478 , 0.37531825, 0.64856213, 0.94368344,
        0.12455872, 0.21219825, 0.14391759, 0.15165705, 0.29783426]])

In [47]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
# Adicionando elementos a um array.
two_dim = np.insert(two_dim,0,10)

In [49]:
# Transforma em um array de uma linha.
two_dim

array([10,  1,  2,  3,  4,  5,  6])

In [50]:
# Apagando o elemento da primeira posição do array.
two_dim = np.delete(two_dim,[0])

In [51]:
two_dim

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Gerando um arquivo .txt a partir de um array
np.savetxt("dataset_array.txt",two_dim, delimiter=',')

## Funções que são úteis e pouco conhecidas

In [10]:
x = np.array([1, 2, 3])
np.repeat(x, 3) # repete o valor dos arrays lado a lado.

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [11]:
np.tile(x, (3, 1)) # repete verticalmente três vezes.

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [12]:
np.flip(x) # inverte a ordem dos elementos do array

array([3, 2, 1])

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [3]:
np.cumprod(x) # produto acumulado de todos os elementos anteriores no array

array([  1,   2,   6,  24, 120], dtype=int32)

In [6]:
np.cumsum(x) # soma acumulada de todos os elementos anteriores no array

array([ 1,  3,  6, 10, 15], dtype=int32)

In [5]:
np.diff(x) # diferença de todos os elementos anteriores no array

array([1, 1, 1, 1])

In [18]:
np.argsort(x) # ordena os índices dos valores ordenados no arrays

array([0, 1, 2, 3, 4], dtype=int64)

In [19]:
x = np.array([2, 1, 5, 4, 3])
np.argsort(x) 

array([1, 0, 4, 3, 2], dtype=int64)

# Acessando Dimensões no Array

In [3]:
# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha,coluna
my_array = np.random.random([10,2])

In [15]:
my_array

array([[0.24086604, 0.03800358],
       [0.56666289, 0.16849406],
       [0.88610751, 0.61639979],
       [0.28597597, 0.36693998],
       [0.84243073, 0.69569194],
       [0.61587687, 0.01269536],
       [0.4769537 , 0.17899383],
       [0.53532086, 0.11690796],
       [0.37425959, 0.94216435],
       [0.38233021, 0.11998666]])

In [16]:
# Imprimindo o primeiro elemento (1 linha)
my_array[0]

array([0.24086604, 0.03800358])

In [17]:
# Imprimindo o primeiro elemento da coluna 0 (1 coluna)
my_array[0][0]

0.24086603995344946

In [18]:
# Primeiro elemento da coluna 1
my_array[0][1]

0.038003579610823124

In [19]:
# Segundo elemento da coluna 1
my_array[1][1]

0.1684940571894099

In [20]:
# Segundo elemento da coluna escrito com virgula.
# O primeiro valor especifica a linha e o segundo valor especifica a coluna.
my_array[1,1]

0.1684940571894099

In [21]:
# Imprimindo até 3 valores da coluna 1
my_array[:3,1]

array([0.03800358, 0.16849406, 0.61639979])

In [22]:
# Imprime todas as linhas da coluna 2 * 10
my_array[:,1] * 10

array([0.3800358 , 1.68494057, 6.16399793, 3.66939976, 6.9569194 ,
       0.12695358, 1.78993834, 1.16907961, 9.42164353, 1.19986657])

In [35]:
# Criando um array multidimensional de exemplo
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [36]:
# Fatiando o array em linhas
primeiras_linhas = array[:2]
ultima_linha = array[2:]

print("Primeiras linhas:")
print(primeiras_linhas)

print("\nÚltima linha:")
print(ultima_linha)

Primeiras linhas:
[[1 2 3]
 [4 5 6]]

Última linha:
[[7 8 9]]


In [37]:
# Fatiando o array em colunas
primeiras_colunas = array[:, :2]
ultima_coluna = array[:, 2:]

print("\nPrimeiras colunas:")
print(primeiras_colunas)

print("\nÚltima coluna:")
print(ultima_coluna)


Primeiras colunas:
[[1 2]
 [4 5]
 [7 8]]

Última coluna:
[[3]
 [6]
 [9]]


In [39]:
n_array = np.arange(1,30,3)
n_array

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [40]:
# imprimir de 1 a 5 pulando 2 numeros
n_array[1:5:2]

array([ 4, 10])

In [43]:
# imprimindo os ímpares
n_array[::2]

array([ 1,  7, 13, 19, 25])

In [42]:
# imprimindo os pares
n_array[1::2]

array([ 4, 10, 16, 22, 28])

In [23]:
# Comparação retorna indices
my_array > 0.50

array([[False, False],
       [ True, False],
       [ True,  True],
       [False, False],
       [ True,  True],
       [ True, False],
       [False, False],
       [ True, False],
       [False,  True],
       [False, False]])

In [24]:
# Acessando valores por índices
my_array[my_array > 0.50]

array([0.56666289, 0.88610751, 0.61639979, 0.84243073, 0.69569194,
       0.61587687, 0.53532086, 0.94216435])

In [46]:
np.sum(my_array[my_array > 0.50])

125.70065493821143

In [4]:
#substituir valores < 0.5
my_array[my_array < 0.50] = 10
my_array

array([[ 0.61276028, 10.        ],
       [ 0.74025059, 10.        ],
       [ 0.87566939,  0.51965075],
       [10.        , 10.        ],
       [10.        , 10.        ],
       [10.        ,  0.64926549],
       [10.        ,  0.60806605],
       [10.        , 10.        ],
       [10.        ,  0.82244374],
       [ 0.59846776, 10.        ]])

In [10]:
my_array = np.random.random([10,2])
print(my_array)
np.where(my_array < 0.50, 10, my_array)

[[0.98824693 0.11398842]
 [0.91903394 0.9718535 ]
 [0.25416624 0.90352602]
 [0.8000327  0.73194675]
 [0.59249154 0.61608158]
 [0.24911995 0.9590603 ]
 [0.84400495 0.33545079]
 [0.50850934 0.01651865]
 [0.33131555 0.57617775]
 [0.73729824 0.79277567]]


array([[ 0.98824693, 10.        ],
       [ 0.91903394,  0.9718535 ],
       [10.        ,  0.90352602],
       [ 0.8000327 ,  0.73194675],
       [ 0.59249154,  0.61608158],
       [10.        ,  0.9590603 ],
       [ 0.84400495, 10.        ],
       [ 0.50850934, 10.        ],
       [10.        ,  0.57617775],
       [ 0.73729824,  0.79277567]])

In [47]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
# somar as linhas, axis = 1
np.sum(array,axis = 1)

array([ 6, 15, 24])

In [49]:
# somar as colunas, axis = 0
np.sum(array,axis = 0)

array([12, 15, 18])

# Carregar Arrays NumPy a partir de arquivos de Texto

In [26]:
# Lendo um arquivo do tipo .txt
dataset = np.loadtxt('dataset_array.txt', delimiter=',')

In [27]:
dataset.shape

(6,)

In [28]:
dataset

array([1., 2., 3., 4., 5., 6.])

In [29]:
# carregando um arquivo dividido em 3 arrays
# utilize o unpack para retornar o elemento transposto
a, b, c = np.loadtxt('dataset_valores.txt', skiprows=1, unpack=True)

In [30]:
# Array a
a

array([0.4839, 0.1292, 0.1781, 0.7676, 0.5993])

In [31]:
# Array B
b

array([0.4536, 0.6875, 0.3049, 0.5801, 0.4357])

In [32]:
# Array C
c

array([0.3561, 0.6565, 0.8928, 0.2038, 0.741 ])

In [33]:
# utilize genfromtxt para arquivos com valores faltantes
# Carrega o arquivo ignorando as 2 primeiras linhas e preenchendo os valores vazio por 0
# Obs: os valores string também são convertidos!!
# utilize filling_values para substituir os valores faltantes ou em strings pelo valor especificado nesta variável

dataset = np.genfromtxt('dataset_valores_vazio.txt', skip_header=2, filling_values=0)

In [34]:
# Imprimindo o dataset
dataset

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.    ],
       [0.1781, 0.3049, 0.8928],
       [0.    , 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])

# Operações Matriciais

In [2]:
a = np.array([100, 200, 300])
print(a)
print(type(a))           
print(a.shape)           
print(a.ndim)            

print(a[0], a[1], a[2])

[100 200 300]
<class 'numpy.ndarray'>
(3,)
1
100 200 300


In [2]:
a[0] = 500                  
print(a)                 

[500 200 300]


In [3]:
b = np.array(
              [
                  [1,2,3],
                  [4,5,6]
              ]
            )  

print(b)
print(b.shape)   
print (b.ndim)   
print(b[0, 0], b[0, 1], b[1, 0])  

[[1 2 3]
 [4 5 6]]
(2, 3)
2
1 2 4


In [4]:
b[0][0] = 2
print(b)

[[2 2 3]
 [4 5 6]]


In [5]:
# Array 3 dimensões

b = np.array( [
                  [
                      [1,2,3],
                      [4,5,6]
                  ],

                  [
                      [1,2,3],
                      [4,5,6]
                  ]
              ]
            )  

print(b)
print(b.shape)  
print (b.ndim)

print (b[0,1,2])

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
3
6


## Operações

### Soma

In [3]:
#   1 2      5 6      6  8
#         +        =    
#   3 4      7 8      10 12 

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print("X:" + str(x) + '\n')
print("Y:" + str(y) + '\n')

# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print()
print(np.add(x, y))


X:[[1. 2.]
 [3. 4.]]

Y:[[5. 6.]
 [7. 8.]]

[[ 6.  8.]
 [10. 12.]]

[[ 6.  8.]
 [10. 12.]]


In [11]:
%%time
print(x + y)

[[ 6.  8.]
 [10. 12.]]
Wall time: 1.06 ms


In [12]:
%%time
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
Wall time: 0 ns


### Subtração

In [13]:
#   1 2      5 6      -4  -4
#         -        =    
#   3 4      7 8      -4  -4 

# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print()
print(np.subtract(x, y))


[[-4. -4.]
 [-4. -4.]]

[[-4. -4.]
 [-4. -4.]]


### Multiplicação

In [14]:
#   1 2      5 6       5  12
#         *        =    
#   3 4      7 8      21  32 

print(x * y)
print()
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]

[[ 5. 12.]
 [21. 32.]]


In [4]:
# Multiplicação matricial
#   1 2      5 6       1*5 + 2*7     1*6 + 2*8
#         x        =    
#   3 4      7 8       3*5 + 4*7     3*6 + 4*8 

print(x.dot(y))
print()
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


### Divisão

In [15]:
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]

#   1 2      5 6       0.2  0.3333
#         /        =    
#   3 4      7 8       0.428  0.5 

print(x / y)
print()
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


### Raíz quadrada

In [16]:
%%time
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]
Wall time: 0 ns


In [17]:
import numpy as np

a = np.zeros((2,2))   # array de zeros
print(a,'\n')              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # array de uns
print(b,'\n')              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # array de constantes
print(c,'\n')               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # matriz identidade
print(d,'\n')              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # array preenchido de valores randomicos entre 0 e 1
print(e,'\n')                    

[[0. 0.]
 [0. 0.]] 

[[1. 1.]] 

[[7 7]
 [7 7]] 

[[1. 0.]
 [0. 1.]] 

[[0.67994065 0.85526581]
 [0.49091336 0.1594161 ]] 



In [18]:
a = np.array(
              [
                [1,2,3,4], 
                [5,6,7,8], 
                [9,10,11,12]
              ]
            )

#print o seguinte array
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

print (b,'\n')



[[2 3]
 [6 7]] 



In [19]:
b = a[1:, 2:]
b

array([[ 7,  8],
       [11, 12]])

In [21]:
a[:,0]

array([1, 5, 9])

In [23]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 11, 12]])

In [22]:
print([a[0, 0], a[1, 1], a[2, 0]])

[1, 6, 9]


In [24]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"


print(a[bool_idx])  # Prints "[3 4 5 6]"

print(a[a > 2])     # Prints "[3 4 5 6]"




[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [25]:
array = np.arange(8)
print("Original array : \n", array)
 
# shape array com 2 linhas e 2 colunas
array = np.arange(4).reshape(2, 2)
print("\narray reshaped with 2 rows and 2 columns : \n", array)

# shape array com 4 linhas e 2 colunas
array = np.arange(8).reshape(4, 2)
print("\narray reshaped with 4 rows and 2 columns : \n", array)
 
# shape array com 2 linhas e 4 colunas
array = np.arange(8).reshape(2 ,4)
print("\narray reshaped with 2 rows and 4 columns : \n", array)
 
# array 3D
array = np.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n", array)


Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 2 columns : 
 [[0 1]
 [2 3]]

array reshaped with 4 rows and 2 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [26]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # cria uma matriz vazia do mesmo shape que x

print (y)

# Add o vetor v a cada linha da matrix x com o loop
for i in range(4):
    y[i, :] = x[i, :] + v

# y
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)



[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
